package com.ephox
package vault
package sql

sealed trait StatementExecute {

}

object StatementExecute {
  case class AutoGeneratedKeys(n: Int) extends StatementExecute
  case class ColumnIndexes(x: List[Int]) extends StatementExecute
  case class ColumnNames(x: List[String]) extends StatementExecute
}
